### ISSUE TITLE
Unexpected token l in JSON at position 1

### ISSUE THREAD

**Issue by stevefusaro** [anvilco/spectaql#204] opened 2022-02-03 17:50 UTC
You can reproduce this error using the following schema.gql file

```
type Query {
  Pets(paginationOptions: PaginationOptions = { limit: 10, offset: 0 }): Pet!
}

input PaginationOptions {
  limit: Int = 10
  offset: Int = 0
}

type Pet {
  name: String!
  limit: Int!
  offset: Int!
}
```

When I wrap `{ limit: 10, offset: 0 }` in quotes the error goes away but this is an issue because our backend service code fails when we do that. This issue looks very similar to https://github.com/anvilco/spectaql/issues/83. I considered creating this issue in the `graphql-2-json-schema` repo but I figured I'd start here.

**Comment by newhouse** [comment] 2022-03-07 22:22
Duplicate of https://github.com/anvilco/spectaql/issues/186

Fixed by https://github.com/anvilco/spectaql/pull/220.

Fix is out in `0.14.0`

**Closed by newhouse** 2022-03-07 22:22 UTC
